bankproject/bankingapp/urls.py
from django.urls import path, include
from.import views
app_name= 'bankingapp'
urlpatterns = [
       path('', views.index, name='index'),
       path('signup',views.signup,name="signup"),
       path('signin',views.signin,name="signin"),
       path('registration',views.registration, name="registration"),
       path('forms',views.forms, name='forms'),
       path('logout',views.logout,name="logout"),
]

bankproject/bankproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
       path('admin/',admin.site.urls),
       path('', include("bankingapp.urls")),
       path('dropdownlist/',include('dropdownlist.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

bankproject/dropdownlist/urls.py
from django.urls.conf import path
from.import views

urlpatterns = [
    path('add/', views.firstname_create_view, name='firstname_add'),
    path('<int:pk>/', views.firstname_update_view, name='firstname_change'),

    path('ajax/load-branch/', views.load_branch, name='ajax_load_branch'),
]

bankproject/bankingapp/models.py
from django.db import models

# Create your models here.
class Login(models.Model):
    name=models.CharField(max_length=250,unique=True)
    password=models.IntegerField()
    class meta:
        ordering=('name')
    def __str__(self):
        return self.name

class Register(models.Model):
    name=models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Registration(models.Model):
    name=models.CharField(max_length=250)

bankproject/dropdownlist/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE


# Create your models here.


class District(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Branch(models.Model):
    district=models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class firstname(models.Model):
    name=models.CharField(max_length=250)
    district=models.ForeignKey(District,on_delete=models.SET_NULL,blank=True,null=True)
    branch=models.ForeignKey(Branch,on_delete=models.SET_NULL,blank=True,null=True)

    def __str__(self):
        return self.name

bankproject/dropdownlist/forms.py
from django import forms

from dropdownlist.models import District, Branch, firstname


class firstnameCreationForm(forms.ModelForm):
    class Meta:
        model = firstname
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Branch.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.district.branch_set.order_by('name')

bankproject/bankingapp/views.py
from django.contrib import messages
from django.contrib.auth import authenticate,login
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User



# Create your views here.
def index(request):
    return render(request,"home.html")

def signup(request):
    if request.method=="POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1=request.POST.get('password1')
        password2 = request.POST.get('password2')

        # myuser = User.objects.create_user(username,email,password1)
        # myuser.save()

        messages.success(request, "Your Account has been successfully created.")
        return redirect('/signin')


    return render(request,'signup.html')

def signin(request):
    if request.method == 'POST':
        username= request.POST['username']
        password = request.POST['password']

        user= authenticate(username=username,password= password)
        if user is not None:
            login(request,user)
            username=user.username
            return render(request,"home.html",{'username:username'})
        else:
            messages.error(request,"False Credentials")
            return redirect('/registration')

    return render(request,'signin.html')

def registration(request):
    if request.method == "POST":
        return redirect('/forms')

    return render(request,"registration.html")

def forms(request):
    if request.method == 'POST':

        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        phone = request.POST['phone']

        myuser = User.objects.create_user(firstname,lastname, email)
        myuser.save()

        messages.success(request, "Your Application is submitted.")
        return redirect('/forms')

        # if User.objects.filter(email=email).exists():
        #     messages.info(request,'email already taken')
        # else:
        #     user= User.objects.create_user(username=username,firstname=firstname,lastname=lastname, email=email, phone=phone)
        #     user.save();

    return render(request,"forms.html")

def logout(request):
    pass

bankproject/dropdownlist/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

import dropdownlist
from .forms import firstnameCreationForm
from .models import firstname, Branch


def firstname_create_view(request):
    form = firstnameCreationForm()
    if request.method == 'POST':
        form = firstnameCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('firstname_add')
    return render(request, 'firstname/forms.html', {'form': form})


def firstname_update_view(request, pk):
    firstname = get_object_or_404(dropdownlist, pk=pk)
    form = firstnameCreationForm(instance=firstname)
    if request.method == 'POST':
        form = firstnameCreationForm(request.POST, instance=firstname)
        if form.is_valid():
            form.save()
            return redirect('firstname_change', pk=pk)
    return render(request, 'firstname/home.html', {'form': form})


# AJAX
def load_branch(request):
    district_id = request.GET.get('district_id')
    branch = Branch.objects.filter(district_id=district_id).all()
    return render(request, 'firstname/branch_dropdown_list_options.html', {'branch': branch})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

bankproject/templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

bankproject/templates/dropdown.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DropDown</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

  <div class="container">
  <div class="card body">
    <br/>
    <br/>
    <br/>

    <div class="row">
    <div class="col-md-4">

        <select name="dist" id="district" class="form-control">
            <option value="0">--Select district--</option>
            {% for item in district  %}
            <option value="{{ item.id }}">{{ item.districtname }}</option>
            {% endfor %}
        </select>
    </div>

    <br/>
    <div class="col-md-4">
        <select name="bran" id="branch" class="form-control">
            <option value="0">--Select branch--</option>
            {% for item in branch  %}
            <option value="{{ item.distid_id }}">{{ item.braname }}</option>
            {% endfor %}
        </select>
    </div>

   </div>
  </div>
</div>
 <script>

$(document).ready(function(){

 var district = $("#district");
 var branch = $("#branch");
 var $options = branch.find('option');
 district.on('change',function(){
    branch.html($options.filter('[value="'+ this.value  +'"]'));
 }).trigger('change');


});
</script>
</body>
</html>

bankproject/templates/footer.html
{% load static %}
<footer>
  <center>
    <img src="{% static 'img/footer.png'%}" alt="footimage">
  </center>
</footer>

<div class="footer navbar-fixed bottom my-footer" >
  <p  class="text-center"> @copy; We Bank tech pvt ltd.All Rights Reserved</p>
</div>

bankproject/templates/forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration page</title>
</head>
<body bgcolor="ghostwhite">
<fieldset>
<br>
<br>
    <center><h1>APPLICATION FORM</h1></center>
    <center>
<form action="/forms" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td>
                First Name:
            </td>
            <td>
                <input type="text" name="firstname" placeholder="Enter your firstname">
            </td>
            <td>
                Last Name:
            </td>

            <td>
                <input type="text" name="lastname" placeholder="Enter your lastname">
            </td>
        </tr>
        <tr>
            <td><br>
                Email Address:
            </td>
            <td><br>
                <input type="email" name="email" placeholder="xyz@gmail.com">
            </td>
        </tr>
        <tr>
            <td><br>
                Date of Birth:
            </td>
            <td><br>
                <input type="date" name="dob" placeholder="Enter your DOB">
            </td>
        </tr>
        <tr>
            <td><br>
            Age:
            </td>
            <td><br>
                <input type="number" name="age" placeholder="Enter your age">
            </td>
        </tr>
        <tr>
            <td><br>
                Gender:
            </td>
            <td><br>
                <input type="radio" name="Gender" value="male">Male
            </td>
            <td><br>
                <input type="radio" name="Gender" value="female">Female
            </td>
            <td><br>
                <input type="radio" name="Gender" value="other"/>Other
            </td>
        </tr>
        <tr>
            <td><br>
            Phone:
            </td>
        <td><br>
            <input type="text" name="country code" value="+91" size="2">
        </td>
        <td><br>
            <input type="text" name="phone" size="10">
        </td>
        </tr>
        <tr>
            <td><br>
                Address:
            </td><br>
            <td>
                <textarea cols="21" rows="5" value="address"></textarea>
            </td>
        </tr>
        <tr>
            <td><br>
                District:
            </td>
            <td><br>
                <select name="district">
                    <option value="-1" selected>select..</option>
                    <option value="ernakulam">ERNAKULAM</option>
                    <option value="kottayam">KOTTAYAM</option>
                    <option value="alappuzha">ALAPPUZHA</option>
                    <option value="pathanamthitta">PATHANAMTHITTA</option>
                    <option value="thiruvananthapuram">THIRUVANANTHAPURAM</option>
                </select>
            </td>
        </tr>
        <tr>
            <td><br>
                Branch:
            </td>
            <td><br>
                <select name="">
                    <option value="-1" selected>select..</option>
                    <option value="aluva">Aluva</option>
                    <option value="palarivattam">Palarivattam</option>
                    <option value="vyttila">Vyttila</option>
                    <option value="aroor">Aroor</option>
                    <option value="thuravoor">Thuravoor</option>
                    <option value="chengannur">Chengannur</option>
                    <option value="thiruvalla">Thiruvalla</option>
                    <option value="aranmula">Aranmula</option>
                    <option value="ettumanoor">Ettumanoor</option>
                    <option value="vaikom">Vaikkom</option>
                    <option value="neyyattikara">Neyyattinkara</option>
                    <option value="attingal">Attingal</option>
                </select>
            </td>
        </tr>
        <tr>
            <td><br>
                Account Type:
            </td>
            <td><br>
                <select name="account type">
                    <option value="-1" selected>select..</option>
                    <option value="savings">Savings account</option>
                    <option value="current">Current account</option>
                    <option value="other">Other</option>

                </select>
            </td>
        </tr>
        <tr>
            <td><br>
                Materials Provide:
            </td>
            <td><br>
                <input type="checkbox" name="Materials[]" value="debit card">Debit Card
            </td>
            <td><br>
                <input type="checkbox" name="Materials[]" value="credit card">Credit Card
            </td>
            <td><br>
                <input type="checkbox" name="Materials[]" value="cheque book">Cheque Book
            </td>
            <td><br>
                <input type="checkbox" name="Materials[]" value="other">Other
            </td>
        </tr>
</table>

        <center><tr div class="button">
            <td colspan="2"><input type="submit" class="submit" value="Register" onclick="return formvalidation"/> </td>

<!--            <td><br>-->
<!--                <input type="submit" value="submit">-->
<!--            </td>-->

<!--             <td>-->
<!--                <input type="button" value="/signin">-->
<!--            </td>-->
        </tr></center>

</form>
        </center>
<center>
{% if messages %}
 {% for message in messages %}
   <div class="alert alert-{{message.tags}} m-2" id="msg" role="alert" >
        <h1 style="color:green">{{message}}<h1>
   </div>
 {% endfor %}
{% endif %}
</center>
<center>
<form action="/signup" method="post">
    {% csrf_token %}
      <table>
          <tr>
              <td>
                  <input type="submit" value="logout">
              </td>
          </tr>
      </table>
    <div class="mt-4">
					<div class="d-flex justify-content-center links">
						 <a href="/" class="ml-2">Back to Home</a>
					</div>
    </form>
<!--    {% for messages in messages %}-->
<!--    <h1> {{message}} </h1>-->
<!--{% endfor %}-->
    </center>
</fieldset>
<form method="post" id="firstnameForm" data-cities-url="{% url 'ajax_load_branch' %}">
    {% csrf_token %}
</form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#firstnameForm").attr("data-branch-url");  // get the url of the `load_branch` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'district_id': districtId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_branch").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (branch) {
                    html_data += `<option value="${branch.id}">${branch.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>

</body>
</html>

bankproject/templates/header.html
{% load static %}
<header>
    <center>
        <img src="{% static 'img/logo.png' %}" alt="logimage">
    </center>
</header>

bankproject/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
        <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div  style=" background-color:lightskyblue; width:100%; height:1000px;">
    <img src="{% static 'img/logo.png' %}" style="width:100px; height:100px;">
<!--    {% include 'header.html' %}-->
{% include 'navbar.html' %}
{% block body %}
    <img src="{% static 'img/header1.png' %}" style="width:100%; height:300px;">
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
</body>
</html>

bankproject/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bankproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link" href="#">Link</a>-->
<!--      </li>-->
      <li class="nav-item dropdown {% if 'bankingapp' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Branch
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Ernakulam</a>
          <a class="dropdown-item" href="#">Kottayam</a>
          <a class="dropdown-item" href="#">Alappuzha</a>
          <a class="dropdown-item" href="#">Pathanamthitta</a>
          <a class="dropdown-item" href="#">Thiruvananthapuram</a>


        </div>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="/signin">Login</a> </button>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="/signup">Register</a></button>
    </form>
  </div>
</nav>

bankproject/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
Welcome to We Bank.
Complete the form correctly to continue
<br>
<center>
    <br>
    <br>
    <form action="registration" method="post">
        {% csrf_token %}
        <div class="d-flex justify-content-center mt-3 login_container">
							<br>
				 			<input class="btn btn-primary" type="submit" value="Fill up the form">
    </form>
</center>
</body>
</html>

bankproject/templates/signin.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
		    height: 300px;
			width: 300px;
			margin-top: 200px;
			margin-bottom: 200px;
			margin-left: 50px;
			background: #74cfbf;
			position: center;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
		   text-align:center;
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title" >LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
								<br>
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						<br>
						Don't have an account? <a href="/signup" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>




<!--<h1> REGISTER HERE!</h1>-->

<!--<form method="post" action="/signin">-->
<!--  {% csrf_token %}-->
<!--    <label> Username </label>-->
<!--    <input type="text" name="username" placeholder="Enter your name" ><br>-->
<!--    <br>-->
<!--    <label>Password </label>-->
<!--    <input type="password" name="password1" placeholder="Enter your password" ><br>-->
<!--    <br>-->
<!--    <button type="submit">Signin</button>-->

<!--</form>-->

bankproject/templates/signup.html
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
		    height: 400px;
			width: 350px;
			margin-top: 100px;
			margin-bottom: 200px;
			margin-left: 50px;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
		   text-align: center;
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title" >REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Enter username">

						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							<input type="email" name="email" placeholder="Enter email">

						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="text" name="password1" placeholder="Create Password">

						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="text" name="password2" placeholder="Confirm Password">

						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">

				 			<input class="btn login_btn" type="submit" value="Register Account">

				   		</div>
					</form>
				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="/signin" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>






<!--<h1> REGISTER HERE!-->
<!--</h1>-->

<!--<form method="post" action="/signup">-->
<!--  {% csrf_token %}-->
<!--    <label> Username </label>-->
<!--    <input type="text" name="username" placeholder="Enter your name"><br>-->
<!--    <label> Email Address</label>-->
<!--    <input type="email" name="email" placeholder="Enter your email"><br>-->
<!--    <label> Create Password </label>-->
<!--    <input type="password" name="password1" placeholder="Create password"><br>-->
<!--    <label> Confirm Password </label>-->
<!--    <input type="password" name="password2" placeholder="Confirm your password"><br>-->
<!--    <br>-->
<!--    <button type="submit">Register</button>-->

<!--</form>-->